config/routes.rb
Rails.application.routes.draw do
  resources :payments ,except: [:destory, :edit, :update]
  root to: 'payments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  # GET /payments or /payments.json
  def index
    @notice=params[:notice]
    @payments = list_payment
  end

  # GET /payments/1 or /payments/1.json
  def show
    @payment = params[:payment].nil? ? get_payment(params[:id]).body.payment : params[:payment]
    @notice=params[:notice]
  end

  # GET /payments/new
  def new
    @notice=params[:notice]
    @price=params[:price]
  end

  # POST /payments or /payments.json
  def create
    @payment=create_payment(params[:nonce],params[:price].to_i)
    respond_to do |format|
      if @payment.success?
        format.html { redirect_to payment_path(@payment.body.payment[:id], payment: @payment.body.payment, notice: "Payment was successfully created." )}
        #format.json { render :show, status: :created, location: @payment }
      else
        format.html { redirect_to action: :new, 'data-turbolinks': false,price: params[:price],notice: "Payment was unprocessable" }
        #format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def get_square_client
    access_token=ENV['SQUARE_ACCESS_TOKEN']
    location_id=ENV['LOCATION_ID']
    case Rails.env
    when"production"
      environment="production"
    else
      environment='sandbox'
    end
    client = Square::Client.new(
      access_token: access_token,
      environment: environment
    )
    return client
  end
  def list_payment
    client=self.get_square_client
    payments=client.payments.list_payments(
      sort_order: "DESC",
      location_id: ENV['LOCATION_ID']
    )
    payments= payments.body.try(:payments).nil? ? [] :payments.body.payments
    return payments #upto 100 paymetns will return
  end
  def create_payment(nonce, price)
    client=self.get_square_client
    location_id=ENV['LOCATION_ID']
    result = client.payments.create_payment(
      body: {
        source_id: nonce,
        idempotency_key: SecureRandom.uuid(),
        amount_money: {
          amount: price,
          currency: "JPY"
        },
        location_id: location_id
      }
    )
    return result
  end
  def get_payment(id)
    client=self.get_square_client
    result = client.payments.get_payment(
      payment_id: id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SqRailsWebPaymentExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container">
	  <%= yield %>
	</div>
    
  </body>
</html>

app/views/payments/_details.html.erb
<div class="container">
	<%details.each do |key,value|%>
		<ul>
			<%if value.class==Hash then %>
				<li>
					<%=key.to_s%>: <%= render partial: 'details', locals: { details: value }%>
				</li>
			<%elsif value.class==Array then %>
				<%value.each_with_index do |hash,index|%>
					<li><%=key.to_s%>:
						<ul>
							<li>
								<%="#{key.to_s}(#{index})"%>
								<%= render partial: 'details', locals: { details: hash }%>
							</li>
						</ul>
					</li>
				<%end%>
			<%else%>
		   		<li>
					<%=key.to_s%>: <%=value%>
				</li>
			<%end%>
		</ul>
	<%end%>
</div>

app/views/payments/index.html.erb
<h1>Payments</h1>
<%= link_to 'New Payment', new_payment_path, 'data-turbolinks': false%>
<table class="table">
  <thead>
    <tr>
      <th>payment_id</th>
	  <th>price</th>
	  <th>card_brand</th>
	  <th>last_4</th>
	  <th>exp_month</th>
	  <th>exp_year</th>
	  <th>action<th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%=payment[:id]%></td>
		<td><%="#{payment[:amount_money][:amount]}(#{payment[:amount_money][:currency]})"%></td>
		<td><%=payment[:card_details][:card][:card_brand]%></td>
		<td><%=payment[:card_details][:card][:last_4]%></td>
		<td><%=payment[:card_details][:card][:exp_month]%></td>
		<td><%=payment[:card_details][:card][:exp_year]%></td>
		<td><%= link_to 'Show', payment_path(payment[:id]) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payments/new.html.erb
<%case Rails.env%>
<%when 'production'%>
	<%= javascript_include_tag "https://web.squarecdn.com/v1/square.js" , 'data-turbolinks-track': 'reload' %>
<%when 'development'%>
	<%= javascript_include_tag "https://sandbox.web.squarecdn.com/v1/square.js" , 'data-turbolinks-track': 'reload' %>
<%end%>

<div class="container">
	<h1>New Payment</h1>
	<p id="notice"><%= @notice %></p>
	<div class="col-md-8 order-md-1">
	  	<%= form_with(id: "payment-form",url: payments_path, method: :post, local: true) do |f| %>
			<div class="mb-3">
				<label for="card" class="form-label">Credit Card</label>
				<div id="card-container"></div>
				<div id="payment-status-container"></div>
				<%= f.hidden_field "card-nonce", name: "nonce" %>
			</div>
			<div class="mb-3">
				<label for="price" class="form-label">Price</label>
				<%= f.text_field "price",class: "form-control"%>
			</div>
	      	<%= f.submit "Pay" ,id: "card-button",class: "btn btn-primary"%>
	    <% end %>
	</div>
	<%= link_to 'Back', payments_path %>
</div>

app/views/payments/show.html.erb
<h1>Details of payment</h1>
<div class="container">
	<p id="notice"><%= @notice %></p>
    
	<%@payment.each do |key,value|%>
		<%= render partial: 'details', locals: { details: {key=>value}} %>
	<%end%>   
   
	<%= link_to 'Back', payments_path %>
</div>